### ISSUE TITLE
Publish to ACR causes ACR webhook push an extra time without tag

### ISSUE THREAD

**Issue by Kimmen** [dotnet/sdk-container-builds#456]
I have recently updated `Microsoft.NET.Build.Containers` from version _0.4.0_  to _7.0.302_ and updated the publish command to publish directly to our Azure Container Registry (ACR). This causes our webhook to fire twice: once with tags and once without tags. 

So it it something with my publish configuration that is causing this?

In Azure Devops the publish command is specified as:
```yml
pool:
  vmImage: ubuntu-latest

steps:
  - task: NuGetAuthenticate@1
    displayName: Access to nuget feed
  - task: Docker@2
    displayName: Access to docker container registry
    inputs:
      containerRegistry: '<company service connection name>'
      command: 'login'
  - task: DotNetCoreCLI@2
    displayName: Publish as container
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/Web.csproj'
      arguments: > 
        -c Release 
        --os linux 
        --arch x64 
        -p:PublishProfile=DefaultContainer 
        -p:ContainerImageName=$(imageName) 
        -p:ContainerImageTag=$(tag)
        -p:ContainerRegistry=$(registry)
      zipAfterPublish: false
      modifyOutputPath: false
```

The tag is just the build-number specified as `$(Date:yyyyMMdd)$(Rev:.r)`

In the Azure Devops logs it looks like it uploads the image once:

>   Uploaded manifest to ***
  Uploading tag 20230602.2 to ***
  Uploaded tag 20230602.2 to ***
  Pushed container 'individualportalapi:20230602.2' to registry '***'

This is the webhook logs:
![image](https://github.com/dotnet/sdk-container-builds/assets/1217354/bb4ee23c-d856-4fb2-9b62-0769f4f9e9c1)
