### ISSUE TITLE
Add authentication for service connection in Azure DevOps

### ISSUE THREAD

**Issue by Varorbc** [dotnet/sdk-container-builds#536]
Add authentication for service connection in Azure DevOps

**Comment by baronfel** [comment]
@Varorbc do you have an example or sample showing this not working? We currently support authentication via Azure Managed Identities, and my understanding was that this was the enabler for AzDo connections.

**Comment by baronfel** [comment]
Interesting - so when you choose the Docker Hub it automatically fills in the index.docker.io URL, hard coding it?

**Comment by baronfel** [comment]
I notice that index.docker.io is specified both in your csproj as well as in the service connection - is the service connection URL hard coded in this case? Does pushing to index.docker.io work if you try publishing locally?

**Comment by mmoles-Growlink** [comment]
Simply put, this will never work.  
```
- task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '.\MyModule.csproj'
      arguments: '-r linux-arm -c Release /t:PublishContainer'
      zipAfterPublish: false
```

To publish, this is what we are required to do.    

```
- task: AzureCLI@2
    inputs:
      azureSubscription: '<mySubscription>'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
                az acr login --user ${env:ACR_USER} --password  ${env:vACR_PASSWORD}  --name mycontainers
                dotnet publish ".\MyModule.csproj"  -r linux-arm -c Release /t:PublishContainer
```
I believe you can also do it with a regular non AzureCLI script as well.  In any case, you need to manually log into the acr.

But there is nothing in devops pipelines that support /t:PublishContainer.
